version: "3"
services:
  #backend:
  #             build: ./backend
  #             ports: 
  #                     - "8000:8000"
  #             volumes:
  #                     - ./backend/src/:/root
  #             environment:
  #                     GOOS: "linux"
  #                     CGO_ENABLED: "1"

        frontend:
                build: ./frontend
                ports:
                        - "3000:3000"
                volumes:
                        - ./frontend/src:/node/src
                        - ./frontend/public:/node/public
                stdin_open: true 
